version: '3'

networks:
  hotel-network:
    driver: bridge

services:
  angular-app:
    image: frontend-img 
    container_name: frontend-img-cont
    build:
      context: ./Frontend 
      dockerfile: Dockerfile 
    ports:
      - "81:80"  
    depends_on:
    - spring-boot-app  
    networks:
      - hotel-network

  spring-boot-app:
    image: backend-img  
    container_name: backend-img-cont
    build:
      context: ./Backend  
      dockerfile: Dockerfile 
    ports:
      - "8081:8080" 
    networks:
      - hotel-network