version: '3'

networks:
  book-network:
    driver: bridge

services:
  angular-app:
    image: book-frontend-img 
    container_name: book-frontend-cont
    build:
      context: ./Frontend 
      dockerfile: Dockerfile 
    ports:
      - "81:80"  
    depends_on:
    - spring-boot-app  
    networks:
      - book-network

  spring-boot-app:
    image: book-backend-img  
    container_name: book-backend-cont
    build:
      context: ./Backend  
      dockerfile: Dockerfile 
    ports:
      - "8081:8080" 
    networks:
      - book-network